system:
    default:
        css:
            files:
                - 'bundles/dpplatformuiextensionskeleton/css/myproject.css'
                - 'bundles/dpplatformuiextensionskeleton/css/randomgif.css'
                - 'bundles/dpplatformuiextensionskeleton/css/serversidehello.css'
