services:
#    dp_platform_ui_extension_skeleton.example:
#        class: DP\PlatformUIExtensionSkeletonBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    dp_platform_ui_extension_skeleton.controller.hello:
        class: DP\PlatformUIExtensionSkeletonBundle\Controller\HelloController
        arguments: ['@templating']

    dp_platform_ui_extension_skeleton.controller.plaformui.hello:
        class: DP\PlatformUIExtensionSkeletonBundle\Controller\PlatformUIHelloController
        parent: ezsystems.platformui.controller.base
