system:
    default:
        yui:
            modules:
                navigationhubview-ez-template:
                    type: 'template'
                    path: "%extension_skeleton.public_dir%/templates/navigationhub.hbt"

                # custom dashboard block
                dp-randomgifviewserviceplugin:
                    path: "%extension_skeleton.public_dir%/js/views/services/plugins/dp-randomgifviewserviceplugin.js"
                    requires: ['ez-viewservicebaseplugin']
                    dependencyOf: ['ez-dashboardblocksviewservice']
                dp-dashboardblockrandomgifplugin:
                    path: "%extension_skeleton.public_dir%/js/views/plugins/dp-dashboardblockrandomgifplugin.js"
                    requires: ['plugin', 'base', 'dp-dashboardblockrandomgifview']
                    dependencyOf: ['ez-dashboardblocksview']
                dp-dashboardblockrandomgifview:
                    path: "%extension_skeleton.public_dir%/js/views/dashboard/dp-dashboardblockrandomgifview.js"
                    requires: ['ez-dashboardblockasynchronousview', 'dpdashboardblockrandomgifview-ez-template', 'ez-asynchronousview']
                dpdashboardblockrandomgifview-ez-template:
                    type: 'template'
                    path: "%extension_skeleton.public_dir%/templates/dashboard/randomgif.hbt"

                # integrating a Symfony action
                dp-hellorouteplugin:
                    path: "%extension_skeleton.public_dir%/js/apps/plugins/dp-hellorouteplugin.js"
                    requires: ['ez-pluginregistry', 'plugin', 'base']
                    dependencyOf: ['ez-platformuiapp']
                dp-hellonavigationplugin:
                    requires: ['ez-pluginregistry', 'ez-viewservicebaseplugin']
                    path: "%extension_skeleton.public_dir%/js/views/services/dp-hellonavigationplugin.js"
                    dependencyOf: ['ez-navigationhubviewservice', 'ez-navigationitemview']

                # field edit tweak
                dp-signcounterplugin:
                    path: "%extension_skeleton.public_dir%/js/views/fields/plugins/dp-signcounterplugin.js"
                    requires: ['ez-pluginregistry', 'plugin', 'base']
                    dependencyOf: ['ez-textblock-editview', 'ez-richtext-editview']
